name: Haskell CI

on: [push, pull_request]
jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.4.3', '9.2.5', '9.0.2', '8.10.7']
        # Unlikely that we'll succeed on windows and fail on macos,
        # including it is just burning CI time. But windows could have
        # path or IO issues, so worth including
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Cabal cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: Cabal update
      run: cabal update
    - name: Build using cabal
      run: cabal build all
    - name: Test
      run: cabal test all

  haskell_post_job:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - run: |
          echo "jobs info: ${{ toJSON(needs) }}"
      - if: contains(needs.*.result, 'failure')
        run: exit 1
      - if: contains(needs.*.result, 'cancelled') && needs.pre_job.outputs.should_skip != 'true'
        run: exit 1
